keywords = {
    "cover_up": [
        "deep state",
        "coverup",
        "cover up",
        "hoax",
        "the deep state"
    ],
    "emergency_responses": [
        "pesticides",
        "lock down",
        "two weeks",
        "stafford act",
        "cdc",
        "quarentine",
        "quarantine",
        "shutdown",
        "stimulus check",
        "filmyourhospital",
        "n95",
        "thermometer"
    ],
    "false_cures": [
        "vitamin c",
        "cebion",
        "tom kawcyznski",
        "gargle salt",
        "vinegar",
        "lysol",
        "herbal tea",
        "hairdryer",
        "hairdryers",
        "avigan",
        "alex jones",
        "nano-silver",
        "nano silver",
        "hair dryer",
        "vaccine",
        "adrenochrome",
        "id2020",
        "chloroquine",
        "hydroxychloroquine",
        "azithromycin",
        "zinc",
        "bill gates",
        "gates",
        "chips",
        "agenda 21"
    ],
    "general": [
        "trump virus",
        "coronachan",
        "rona",
        "coronavirus",
        "pandemic",
        "cov-19",
        "cov19",
        "cov",
        "corona",
        "virus",
        "covid",
        "covid-19",
        "covid19",
        "liberate"
    ],
    "nature_of_the_virus": [
        "ibuprofen",
        "walter pascale",
        "children immune",
        "immune",
        "hand-sanitizer",
        "contamination",
        "smoking",
        "sars2",
        "5g"
    ],
    "other": [
        "fire fauci",
        "fauci",
        "hidden corona"
    ],
    "racist_assocations": [
        "chinkflu",
        "chunkvirus",
        "coofening",
        "holocough",
        "kung flu",
        "wuflu",
        "chink flu",
        "chink aids",
        "yellow fever",
        "chink virus",
        "gook flu",
        "gook plague",
        "gook virus",
        "china town",
        "chinatown",
        "adl",
        "wu-tang flu",
        "wuhan flu-han",
        "ching chong's coughing syndrome",
        "ching chong coughing syndrome"
    ],
    "status_of_individuals": [
        "oprah winfrey",
        "oprah",
        "tom hanks",
        "weinstein",
        "harvey weinstein",
        "obama",
        "soros",
        "george soros",
        "clinton"

    ],
    "virus_origin": [
        "dean koontz",
        "wuhan-400",
        "virus origin",
        "eating bats",
        "bat soup",
        "wuhan",
        "wuhanvirus",
        "wuhan virus",
        "american flu"
    ],
    "weaponization": [
        "biological warfare",
        "bioweapon"
    ],
    "self_labeling": [
        "conspiracy",
        "conpiratorial",
        "conspiracy theory",
        "conspiracies"],
    "qanon": [
        "q",
        "qanon",
        "anon"],
    "secret_society": [
        "council on foreign relations",
        "cofr",
        "illuminati",
        "cabal",
        "mind control",
        "mind-control"]
}

