    check_list = ['spanish flu','Quarantine', 'Italy','social distance','pandemic',
    'epidemic','lockdown','Wuhanlockdown','Koronavirus','bio','CDC','breakdown','China',
    'WuhanVirus','COVID19','chinese lab','shut down','military','corona', 'coronavirus',
    'virus', 'Iran', 'china', 'biological-weapon','biological weapon','bio-weapon',
    'bioweapon','coronavirus','covid19' ,'coronavirusoutbreak','covid_19','covidー19','coronaviruspandemic'
    ,'coronavirusupdate','covid2019','coronavirusupdates','corona','coronaoutbreak','covid',
    'coronavirusindia','coronavirusuk','coronavirussa','coronavirusitalia','cuarentenacoronavirus',
    'china','coronavirusfrance','trump','coronavirusesp','yomequedoencasa','coronavirususa',
    'coronavirusinindia','coronavid19','coronapocalypse','pandemic','coronavirusde','coronapocolypse',
    'coronaviruschallenge','coronavirusespana','coronaalert','trumpliesaboutcoronavirus','coronavirusenchile',
    'wuhancoronavirus','breaking','coronavirusenfrance','coronavirusturkey','coronavirusargentina','pandemia',
    'virus','socialdistancing','coronavirusbrasil','codvid19','coronavirusitaly','quarantinelife',
    'wuhanvirus','coronavirusinsa','coronavirusenargentina','stayhome','covid19italia','coronaviruspakistan',
    'covid19italia','coronaviruspakistan','trumpvirus','coronaviruschile','usa','health',
    'wuhan','coronavirusinkenya','sarscov2','coronavirusinpakistan','coronavirusfr','coronavirusnederland',
    'coronavirusnl','covid19france','coronavirusaustralia','coronavirusdeutschland','coronavirusitalla',
    'coronavirusindonesia','coronavirusencolombia','coronavirusireland','covid19india','flattenthecurve',
    'lockdown','coronavirusu','washyourhands','who','covidー19uk','covd19','coronvirus',
    'koronawirus','chinesevirus','stayathome','confinementtotal','koronavirus','korona','trump','selfisolation',
    'wuhan','コロナ','电晕','武汉市','Chinese virus','chinese-virus']